version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore devDependencies changes
      - dependency-name: "@types/*"
      - dependency-name: "eslint*"
      - dependency-name: "styled-components"
